"""Added goal_type to User

Revision ID: 31263370f4d1
Revises: 62d8fa08f46e
Create Date: 2024-04-07 18:41:37.675547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31263370f4d1'
down_revision = '62d8fa08f46e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('exercise', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_plan')
    # ### end Alembic commands ###
