"""Remove start and end times from challenges

Revision ID: 5f1ac018dcb0
Revises: 7f6d3a3fac13
Create Date: 2024-04-28 01:36:41.235481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f1ac018dcb0'
down_revision = '7f6d3a3fac13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.drop_column('start_time')
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('start_time', sa.DATETIME(), nullable=False))

    # ### end Alembic commands ###
