"""InSecond migrate

Revision ID: 62d8fa08f46e
Revises: cc289d862f99
Create Date: 2024-04-06 00:07:04.749649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62d8fa08f46e'
down_revision = 'cc289d862f99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height_feet', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('height_inches', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weight_pounds', sa.Float(), nullable=True))
        batch_op.drop_column('height')
        batch_op.drop_column('weight')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.FLOAT(), nullable=True))
        batch_op.drop_column('weight_pounds')
        batch_op.drop_column('height_inches')
        batch_op.drop_column('height_feet')

    # ### end Alembic commands ###
