"""empty message

Revision ID: 7f6d3a3fac13
Revises: 8d10f1f598d4
Create Date: 2024-04-27 23:09:06.571037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f6d3a3fac13'
down_revision = '8d10f1f598d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_challenges_easy', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('completed_challenges_medium', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('completed_challenges_hard', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('challenge_streak', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('challenge_streak')
        batch_op.drop_column('completed_challenges_hard')
        batch_op.drop_column('completed_challenges_medium')
        batch_op.drop_column('completed_challenges_easy')

    op.drop_table('challenge')
    # ### end Alembic commands ###
